[tox]
minversion = 1.6
envlist = docs,docs-linkcheck
skipsdist = true

[testenv:docs]
basepython = python3.13
deps =
    setuptools>=65.0.0
    -r{toxinidir}/requirements-docs.txt
    -chttps://git.onap.org/doc/plain/etc/upper-constraints.onap.txt
commands =
    sphinx-build -q -b html -n -d {envtmpdir}/doctrees ./ {toxinidir}/_build/html
allowlist_externals =
    git
    sh

[testenv:docs-linkcheck]
basepython = python3.13
deps =
    setuptools>=65.0.0
    -r{toxinidir}/requirements-docs.txt
    -chttps://git.onap.org/doc/plain/etc/upper-constraints.onap.txt
commands = echo "Link checking not enforced"
#commands = sphinx-build -q -b linkcheck -d {envtmpdir}/doctrees ./ {toxinidir}/_build/linkcheck
allowlist_externals = echo
